CREATE TABLE `parana_data_transfer_task` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `type` int(11) NOT NULL COMMENT '1-导出, 2-导入',
  `name` varchar(256) NOT NULL DEFAULT '' COMMENT '数据名称-对应程序中的importer/exporter',
  `display_name` varchar(256) DEFAULT NULL,
  `desc` varchar(256) DEFAULT NULL COMMENT '任务描述',
  `user_id` int(19) DEFAULT NULL,
  `user_name` varchar(64) DEFAULT NULL,
  `user_nickname` varchar(64) DEFAULT NULL COMMENT '用户昵称',
  `criteria_json` text COMMENT '执行参数',
  `file_path` varchar(512) DEFAULT NULL COMMENT '文件地址(ossFileKey)',
  `error_records_path` varchar(512) DEFAULT NULL COMMENT '出错记录的文件地址(ossFileKey)',
  `file_ext` varchar(16) DEFAULT NULL COMMENT '文件扩展名',
  `success_count` int(11) DEFAULT NULL COMMENT '导入/导出成功行数',
  `error_count` int(11) DEFAULT NULL COMMENT '导入/导出失败行数',
  `status` int(11) NOT NULL DEFAULT '0' COMMENT '-100=已取消，-2=超时, -1=失败，0=等待，1=执行中，2=已完成，3=已删除',
  `message` text COMMENT '出错时的错误信息',
  `extra_json` text COMMENT '额外信息',
  `started_at` datetime DEFAULT NULL COMMENT '任务开始时间',
  `finished_at` datetime DEFAULT NULL COMMENT '任务完成时间',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `type` (`type`),
  KEY `name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
